# Codecov configuration to make it a bit less noisy
codecov:
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  require_ci_to_pass: yes
  notify:
    after_n_builds: 23
    wait_for_ci: yes
  # https://docs.codecov.io/docs/codecov-yaml#section-expired-reports
  max_report_age: off

coverage:
  precision: 0  # 2 = xx.xx%, 0 = xx%
  round: nearest # how coverage is rounded: down/up/nearest
  range: 40...100 # custom range of coverage colors from red -> yellow -> green
  status:
    # https://codecov.readme.io/v1.0/docs/commit-status
    project:
      default:
        target: 99% # specify the target coverage for each commit status
        threshold: 30% # allow this little decrease on project
        # https://github.com/codecov/support/wiki/Filtering-Branches
        # branches: master
        if_ci_failed: error
    # https://github.com/codecov/support/wiki/Patch-Status
    patch:
      default:
        target: 50% # specify the target "X%" coverage to hit
        threshold: 5% # allow this much decrease on patch
    changes: false
ignore:
  - "UmbrellaPipeline/data"